import fs from 'fs';
import path from 'path';

// Define the file extensions we want to process
const extensions: string[] = ['.tsx', '.ts', '.css'];

/**
 * Reads a file and replaces absolute paths with relative ones.
 */
function fixPaths(filePath: string): void {
  try {
    const originalContent: string = fs.readFileSync(filePath, 'utf8');
    let content: string = originalContent;

    // 1. Fix general image paths in JSX/TSX 
    // Matches "/img/" and replaces with "./img/"
    // Added a safety check to ensure we don't replace paths that already start with "."
    content = content.replace(/(?<!\.)\/img\//g, './img/');

    // 2. Fix CSS background URLs
    // Covers deep relative paths often generated by build tools
    content = content.replace(/url\(['"]?(\.\.\/)+static\/img\//g, 'url(./img/');
    // Covers absolute paths in CSS
    content = content.replace(/url\(['"]?\/img\//g, 'url(./img/');

    // Only write to disk if changes were actually made
    if (content !== originalContent) {
      fs.writeFileSync(filePath, content, 'utf8');
      console.log(`✅ Fixed paths in: ${filePath}`);
    }
  } catch (error) {
    console.error(`❌ Error processing file ${filePath}:`, error);
  }
}

/**
 * Recursively walks through a directory.
 */
function walkDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    console.warn(`Directory not found: ${dir}`);
    return;
  }

  const files = fs.readdirSync(dir);

  files.forEach((file: string) => {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      walkDir(fullPath);
    } else if (extensions.includes(path.extname(fullPath))) {
      fixPaths(fullPath);
    }
  });
}

// Start execution
console.log('🚀 Starting asset path fix...');
walkDir('./src');
console.log('✨ Asset paths check complete!');
